// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesApp.Models;

#nullable disable

namespace QuotesApp.Migrations
{
    [DbContext(typeof(QuoteContext))]
    partial class QuoteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuotesApp.Models.Like", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikeId"));

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LikeId");

                    b.HasIndex("QuoteId");

                    b.ToTable("Like");

                    b.HasData(
                        new
                        {
                            LikeId = 1,
                            QuoteId = 8,
                            UserId = 123
                        },
                        new
                        {
                            LikeId = 2,
                            QuoteId = 8,
                            UserId = 123
                        },
                        new
                        {
                            LikeId = 3,
                            QuoteId = 8,
                            UserId = 123
                        },
                        new
                        {
                            LikeId = 4,
                            QuoteId = 8,
                            UserId = 123
                        },
                        new
                        {
                            LikeId = 5,
                            QuoteId = 2,
                            UserId = 123
                        },
                        new
                        {
                            LikeId = 6,
                            QuoteId = 2,
                            UserId = 123
                        },
                        new
                        {
                            LikeId = 7,
                            QuoteId = 4,
                            UserId = 123
                        });
                });

            modelBuilder.Entity("QuotesApp.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteId"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("QuoteId");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            QuoteId = 1,
                            Author = "John Wooden",
                            Content = "Things work out best for those who make the best of how things work out.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(444)
                        },
                        new
                        {
                            QuoteId = 2,
                            Author = "Jim Rohn",
                            Content = "If you are not willing to risk the usual you will have to settle for the ordinary.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(542)
                        },
                        new
                        {
                            QuoteId = 3,
                            Author = "Walt Disney",
                            Content = "All our dreams can come true if we have the courage to pursue them.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(546)
                        },
                        new
                        {
                            QuoteId = 4,
                            Author = "Winston Churchill",
                            Content = "Success is walking from failure to failure with no loss of enthusiasm.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(549)
                        },
                        new
                        {
                            QuoteId = 5,
                            Author = "Proverb",
                            Content = "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(552)
                        },
                        new
                        {
                            QuoteId = 6,
                            Author = "Chris Grosser",
                            Content = "Opportunities don't happen, you create them.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(555)
                        },
                        new
                        {
                            QuoteId = 7,
                            Author = "Winston Churchill",
                            Content = "If you're going through hell keep going.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(557)
                        },
                        new
                        {
                            QuoteId = 8,
                            Author = "Anonymous",
                            Content = "Don't raise your voice, improve your argument.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(560)
                        },
                        new
                        {
                            QuoteId = 9,
                            Author = "Anonymous",
                            Content = "Do one thing every day that scares you.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(563)
                        },
                        new
                        {
                            QuoteId = 10,
                            Author = "Lolly Daskal",
                            Content = "Life is not about finding yourself. Life is about creating yourself.",
                            LastModified = new DateTime(2023, 11, 16, 22, 13, 31, 584, DateTimeKind.Local).AddTicks(566)
                        });
                });

            modelBuilder.Entity("QuotesApp.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Name = "Funny"
                        },
                        new
                        {
                            TagId = 2,
                            Name = "Philosophical"
                        },
                        new
                        {
                            TagId = 3,
                            Name = "Serious"
                        },
                        new
                        {
                            TagId = 4,
                            Name = "Educational"
                        },
                        new
                        {
                            TagId = 5,
                            Name = "Motivational"
                        });
                });

            modelBuilder.Entity("QuotesApp.Models.TagAssignment", b =>
                {
                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("QuoteId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TagAssignments");
                });

            modelBuilder.Entity("QuotesApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuotesApp.Models.Like", b =>
                {
                    b.HasOne("QuotesApp.Models.Quote", "Quote")
                        .WithMany("Likes")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuotesApp.Models.TagAssignment", b =>
                {
                    b.HasOne("QuotesApp.Models.Quote", "Quote")
                        .WithMany("TagAssignments")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuotesApp.Models.Tag", "Tag")
                        .WithMany("TagAssignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QuotesApp.Models.Quote", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("QuotesApp.Models.Tag", b =>
                {
                    b.Navigation("TagAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
